# Generated by Django 5.2.6 on 2026-01-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loan_status_loanapplicationdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='business_assets_value',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='citizenship_number',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='co_applicant_relationship',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='course_program',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='down_payment_amount',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='existing_debts',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='family_members_count',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='monthly_household_income',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='parent_guardian_income',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='scholarship_amount',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='tuition_fee',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdetail',
            name='years_in_business',
        ),
        migrations.AddField(
            model_name='loan',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_plan',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_registration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_applicant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_applicant_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='construction_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='course_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='crop_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='existing_emi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='existing_loans',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='farming_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='farming_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='guardian_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='institution_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='irrigation_facility',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='land_documents',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='land_ownership',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='personal_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='property_documents',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='property_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loan',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='admission_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='business_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='business_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='business_registration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='co_applicant_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='construction_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='course_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='course_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='existing_emi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='guardian_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='institution_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='personal_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='property_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplicationdetail',
            name='student_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
