# Generated by Django 5.2.6 on 2026-01-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('home', 'Home Loan'), ('education', 'Education Loan'), ('business', 'Business Loan'), ('agriculture', 'Agriculture Loan')], default='personal', max_length=50),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
