# Generated by Django 5.2.6 on 2026-01-17 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loan_duration_months_loan_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LoanApplicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_number', models.CharField(blank=True, max_length=50)),
                ('family_members_count', models.IntegerField(blank=True, null=True)),
                ('monthly_household_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('existing_debts', models.TextField(blank=True)),
                ('property_location', models.CharField(blank=True, max_length=100)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('down_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('co_applicant_name', models.CharField(blank=True, max_length=100)),
                ('co_applicant_relationship', models.CharField(blank=True, max_length=50)),
                ('property_documents', models.TextField(blank=True)),
                ('institution_name', models.CharField(blank=True, max_length=100)),
                ('course_program', models.CharField(blank=True, max_length=100)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scholarship_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parent_guardian_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50)),
                ('business_registration_number', models.CharField(blank=True, max_length=50)),
                ('years_in_business', models.IntegerField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('business_assets_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('business_plan', models.TextField(blank=True)),
                ('land_area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=50)),
                ('farming_experience_years', models.IntegerField(blank=True, null=True)),
                ('irrigation_facility', models.BooleanField(default=False)),
                ('previous_harvest_details', models.TextField(blank=True)),
                ('equipment_owned', models.TextField(blank=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.loan')),
            ],
        ),
    ]
